// packages/react/src/components/Bold/ArrowLeft3.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgArrowLeft3 = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="m7.42 13.59 7.33 4.23a1.83 1.83 0 0 0 2.75-1.59V7.77a1.83 1.83 0 0 0-2.75-1.59l-7.33 4.23a1.83 1.83 0 0 0 0 3.18Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgArrowLeft3);
export default ForwardRef;

// packages/vue/src/components/Bold/ArrowLeft3.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="m7.42 13.59 7.33 4.23a1.83 1.83 0 0 0 2.75-1.59V7.77a1.83 1.83 0 0 0-2.75-1.59l-7.33 4.23a1.83 1.83 0 0 0 0 3.18Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ArrowLeft3",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
  },
});
</script>
