// packages/react/src/components/Bold/UserCircle2.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUserCircle2 = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2.25A9.75 9.75 0 1 0 21.75 12 9.76 9.76 0 0 0 12 2.25Zm6 15.42a7.49 7.49 0 0 0-12 0 8.25 8.25 0 1 1 12 0Z"
    />
    <path
      fill="currentColor"
      d="M12 6.19A2.81 2.81 0 1 0 14.81 9 2.798 2.798 0 0 0 12 6.19Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUserCircle2);
export default ForwardRef;

// packages/vue/src/components/Bold/UserCircle2.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="M12 2.25A9.75 9.75 0 1 0 21.75 12 9.76 9.76 0 0 0 12 2.25Zm6 15.42a7.49 7.49 0 0 0-12 0 8.25 8.25 0 1 1 12 0Z"
    />
    <path
      fill="currentColor"
      d="M12 6.19A2.81 2.81 0 1 0 14.81 9 2.798 2.798 0 0 0 12 6.19Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "UserCircle2",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
  },
});
</script>
