// packages/react/src/components/Bold/User1.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser1 = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm5 3H7a2.5 2.5 0 0 0 0 5h10a2.5 2.5 0 0 0 0-5Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUser1);
export default ForwardRef;

// packages/vue/src/components/Bold/User1.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="M12 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm5 3H7a2.5 2.5 0 0 0 0 5h10a2.5 2.5 0 0 0 0-5Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "User1",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>
