// packages/vue/src/components/Bold/ArrowDown2.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="M12 15.5a.741.741 0 0 1-.53-.22L6 9.78a.75.75 0 0 1 1-1.06l5 5 5-5a.75.75 0 0 1 1 1.06l-5.5 5.5a.74.74 0 0 1-.5.22Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ArrowDown2",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>

// packages/react/src/components/Bold/ArrowDown2.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgArrowDown2 = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 15.5a.74.74 0 0 1-.53-.22L6 9.78a.75.75 0 0 1 1-1.06l5 5 5-5a.75.75 0 0 1 1 1.06l-5.5 5.5a.74.74 0 0 1-.5.22Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgArrowDown2);
export default ForwardRef;
