// packages/vue/src/components/Bold/Eye.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="m20.09 10.58-2.43-2.42a8 8 0 0 0-11.32 0l-2.43 2.42a2 2 0 0 0 0 2.83l2.43 2.43a8 8 0 0 0 11.32 0l2.43-2.43a2.001 2.001 0 0 0 0-2.83ZM12 14.91a2.91 2.91 0 1 1 0-5.821 2.91 2.91 0 0 1 0 5.821Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Eye",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
  },
});
</script>

// packages/react/src/components/Bold/Eye.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgEye = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="m20.09 10.58-2.43-2.42a8 8 0 0 0-11.32 0l-2.43 2.42a2 2 0 0 0 0 2.83l2.43 2.43a8 8 0 0 0 11.32 0l2.43-2.43a2.001 2.001 0 0 0 0-2.83ZM12 14.91a2.91 2.91 0 1 1 0-5.821 2.91 2.91 0 0 1 0 5.821Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgEye);
export default ForwardRef;
