// packages/vue/src/components/Bold/Heart1.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      fill="currentColor"
      d="M16.74 4A4.5 4.5 0 0 0 12 8.46 4.5 4.5 0 0 0 7.26 4 4.69 4.69 0 0 0 3 8.81C3 16.56 9.35 19.28 11.38 20c.403.131.837.131 1.24 0 2-.67 8.35-3.39 8.38-11.14A4.69 4.69 0 0 0 16.74 4Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Heart1",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>

// packages/react/src/components/Bold/Heart1.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgHeart1 = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      fill="currentColor"
      d="M16.74 4A4.5 4.5 0 0 0 12 8.46 4.5 4.5 0 0 0 7.26 4 4.69 4.69 0 0 0 3 8.81C3 16.56 9.35 19.28 11.38 20c.403.131.837.131 1.24 0 2-.67 8.35-3.39 8.38-11.14A4.69 4.69 0 0 0 16.74 4Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgHeart1);
export default ForwardRef;
