// packages/react/components/cross.tsx
import * as React from "react";
import { SVGProps, Ref, forwardRef } from "react";
const SvgCross = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    ref={ref}
    {...props}
  >
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
    >
      <path d="m8.46 8.46 7.08 7.08M15.54 8.46l-7.08 7.08" />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgCross);
export default ForwardRef;

// packages/vue/components/Cross.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Cross">
      <path
        id="Vector"
        d="M8.46001 8.46L15.54 15.54"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M15.54 8.46L8.46001 15.54"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Cross",
};
</script>
