// packages/react/src/components/ImageSlash.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgImageSlash = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
    >
      <path d="M4.12 19.77A4 4 0 0 1 3 17V7a4 4 0 0 1 4-4h10a4 4 0 0 1 2.75 1.1M21 7v10a4 4 0 0 1-4 4H8" />
      <path d="M12.19 16a2 2 0 0 0 2.22-.41L21 9M3 17l3.59-3.59a2 2 0 0 1 2.82 0M22 2 2 22" />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgImageSlash);
export default ForwardRef;

// packages/vue/components/Image-Slash.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Image-Slash">
      <path
        id="Vector"
        d="M4.12 19.77C3.40289 19.026 3.00152 18.0333 3 17V7C3 5.93913 3.42143 4.92172 4.17157 4.17157C4.92172 3.42143 5.93913 3 7 3H17C18.0236 3.00128 19.0079 3.39496 19.75 4.1"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M21 7V17C21 18.0609 20.5786 19.0783 19.8284 19.8284C19.0783 20.5786 18.0609 21 17 21H8"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M12.19 16C12.5583 16.1632 12.9673 16.2113 13.3634 16.1382C13.7595 16.065 14.1243 15.874 14.41 15.59L21 9"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_4"
        d="M3 17L6.59 13.41C6.96473 13.0375 7.47163 12.8284 8 12.8284C8.52837 12.8284 9.03527 13.0375 9.41 13.41"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_5"
        d="M22 2L2 22"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Image-Slash",
};
</script>
