// packages/react/src/components/Linear/Sun.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgSun = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeMiterlimit={10}
      strokeWidth={1.5}
      d="M12 17.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11Z"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeMiterlimit={10}
      strokeWidth={1.5}
      d="M12 4V2M6.34 6.34 4.93 4.93M4 12H2m4.34 5.66-1.41 1.41M12 20v2m5.66-4.34 1.41 1.41M20 12h2m-4.34-5.66 1.41-1.41"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgSun);
export default ForwardRef;

// packages/vue/components/Sun.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Sun">
      <path
        id="Vector"
        d="M12 17.5C15.0376 17.5 17.5 15.0376 17.5 12C17.5 8.96243 15.0376 6.5 12 6.5C8.96243 6.5 6.5 8.96243 6.5 12C6.5 15.0376 8.96243 17.5 12 17.5Z"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
      />
      <path
        id="Vector_2"
        d="M12 4V2"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_3"
        d="M6.33999 6.33999L4.92999 4.92999"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_4"
        d="M4 12H2"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_5"
        d="M6.33999 17.66L4.92999 19.07"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_6"
        d="M12 20V22"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_7"
        d="M17.66 17.66L19.07 19.07"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_8"
        d="M20 12H22"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
      <path
        id="Vector_9"
        d="M17.66 6.33999L19.07 4.92999"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-miterlimit="10"
        stroke-linecap="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Sun",
};
</script>
