// packages/react/src/components/Linear/Trash.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgTrash = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m6 6.94.75 11.12a2 2 0 0 0 2 2h6.5a2 2 0 0 0 2-2L18 6.94m-4.5 5.62v4.5m-3-4.5v4.5M5 6.94h14m-4.5 0v-2a1 1 0 0 0-1-1h-3a1 1 0 0 0-1 1v2"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgTrash);
export default ForwardRef;

// packages/vue/components/Trash.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Trash">
      <path
        id="Vector"
        d="M6 9.13L6.75 18.13C6.75 18.6604 6.96071 19.1691 7.33579 19.5442C7.71086 19.9193 8.21957 20.13 8.75 20.13H15.25C15.7804 20.13 16.2891 19.9193 16.6642 19.5442C17.0393 19.1691 17.25 18.6604 17.25 18.13L18 9.13"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M13.5 12.63V17.12"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M10.5 12.63V17.12"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_4"
        d="M5 6.88H19"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_5"
        d="M14.5 6.88V4.88C14.5 4.61479 14.3946 4.36043 14.2071 4.1729C14.0196 3.98536 13.7652 3.88 13.5 3.88H10.5C10.2348 3.88 9.98043 3.98536 9.79289 4.1729C9.60536 4.36043 9.5 4.61479 9.5 4.88V6.88"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Trash",
};
</script>
