// packages/react/src/components/Linear/User1Tick.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser1Tick = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M11.03 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM13 19H6a2.51 2.51 0 0 1-2.5-2.5A2.51 2.51 0 0 1 6 14h7m2.47 2.43L17.03 18l3.44-3.44"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUser1Tick);
export default ForwardRef;

// packages/vue/components/User-1-Tick.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="User-1-Tick">
      <path
        id="Vector"
        d="M11.03 11C12.6869 11 14.03 9.65685 14.03 8C14.03 6.34315 12.6869 5 11.03 5C9.37318 5 8.03003 6.34315 8.03003 8C8.03003 9.65685 9.37318 11 11.03 11Z"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M13 19H6C5.33777 18.9974 4.70341 18.7331 4.23514 18.2649C3.76687 17.7966 3.50263 17.1622 3.5 16.5C3.50263 15.8378 3.76687 15.2034 4.23514 14.7351C4.70341 14.2669 5.33777 14.0026 6 14H13"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M15.47 16.43L17.03 18L20.47 14.56"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "User-1-Tick",
};
</script>
