// packages/react/src/components/Linear/User2Tick.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser2Tick = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M11.5 9.75a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm3 10.5H5.94A1.94 1.94 0 0 1 4 18.31v-3.62a1.94 1.94 0 0 1 1.94-1.94h8.56m.5 3.12 1.57 1.56L20 14"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUser2Tick);
export default ForwardRef;

// packages/vue/components/User-2-Tick.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="User-2-Tick">
      <path
        id="Vector"
        d="M11.5 9.75C13.1569 9.75 14.5 8.40685 14.5 6.75C14.5 5.09315 13.1569 3.75 11.5 3.75C9.84315 3.75 8.5 5.09315 8.5 6.75C8.5 8.40685 9.84315 9.75 11.5 9.75Z"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M14.5 20.25H5.94C5.42548 20.25 4.93203 20.0456 4.56821 19.6818C4.20439 19.318 4 18.8245 4 18.31V14.69C4 14.1755 4.20439 13.682 4.56821 13.3182C4.93203 12.9544 5.42548 12.75 5.94 12.75H14.5"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M15 15.87L16.57 17.43L20 14"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "User-2-Tick",
};
</script>
