// packages/react/src/components/User3Plus.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser3Plus = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M10.88 10.88a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm-7.5 8.24v-3.31a2 2 0 0 1 1.93-1.94h10.07m3 5.25v-4.5m-2.25 2.25h4.5"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUser3Plus);
export default ForwardRef;

// packages/vue/components/User-3-Plus.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="User-3-Plus">
      <path
        id="Vector"
        d="M10.88 10.88C12.5369 10.88 13.88 9.53685 13.88 7.88C13.88 6.22315 12.5369 4.88 10.88 4.88C9.22315 4.88 7.88 6.22315 7.88 7.88C7.88 9.53685 9.22315 10.88 10.88 10.88Z"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M3.38 19.12V15.81C3.39495 15.3019 3.60279 14.8186 3.96128 14.4583C4.31977 14.0979 4.80201 13.8876 5.31 13.87H15.38"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M18.38 19.12V14.62"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_4"
        d="M16.13 16.87H20.63"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "User-3-Plus",
};
</script>
