// packages/vue/src/components/Arrow-Down-3.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="m13.3 15.75 3.46-6a1.5 1.5 0 0 0-1.3-2.25H8.54a1.5 1.5 0 0 0-1.3 2.25l3.46 6a1.499 1.499 0 0 0 2.6 0Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "Arrow-Down-3",
  props: {
    width: {
      required: false,
      type: Number,
      default: () => 16,
    },
    height: {
      required: false,
      type: Number,
      default: () => 16,
    },
  },
});
</script>

// packages/react/src/components/Linear/ArrowDown3.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgArrowDown3 = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width="1em"
    height="1em"
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m13.44 16.15 3.83-6.64A1.66 1.66 0 0 0 15.84 7H8.16a1.66 1.66 0 0 0-1.43 2.51l3.83 6.64a1.66 1.66 0 0 0 2.88 0Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgArrowDown3);
export default ForwardRef;
