// packages/vue/components/Microphone.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Microphone">
      <path
        id="Vector"
        d="M15.5 5.5C15.5 3.567 13.933 2 12 2C10.067 2 8.5 3.567 8.5 5.5V10.5C8.5 12.433 10.067 14 12 14C13.933 14 15.5 12.433 15.5 10.5V5.5Z"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M18.5 10.5C18.5 12.2239 17.8152 13.8772 16.5962 15.0962C15.3772 16.3152 13.7239 17 12 17C10.2761 17 8.62279 16.3152 7.40381 15.0962C6.18482 13.8772 5.5 12.2239 5.5 10.5"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_3"
        d="M12 17V22"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_4"
        d="M11 5H13"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_5"
        d="M11 8H13"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Microphone",
};
</script>

// packages/react/src/components/Linear/Microphone.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgMicrophone = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M15.5 5.5a3.5 3.5 0 1 0-7 0v5a3.5 3.5 0 1 0 7 0v-5Z"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M18.5 10.5a6.5 6.5 0 1 1-13 0M12 17v5M11 5h2m-2 3h2"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgMicrophone);
export default ForwardRef;
