// packages/vue/components/Power.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Power">
      <path
        id="Vector"
        d="M15 6.73999C16.291 7.41166 17.3193 8.49716 17.9201 9.82262C18.521 11.1481 18.6596 12.6369 18.3139 14.0505C17.9682 15.4641 17.158 16.7208 16.0133 17.6194C14.8685 18.5179 13.4553 19.0063 12 19.0063C10.5447 19.0063 9.13151 18.5179 7.98674 17.6194C6.84196 16.7208 6.03183 15.4641 5.6861 14.0505C5.34036 12.6369 5.47902 11.1481 6.07987 9.82262C6.68071 8.49716 7.70898 7.41166 9 6.73999"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M12 5V11"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Power",
};
</script>

// packages/react/src/components/Linear/Power.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgPower = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M15 6.74a6.5 6.5 0 1 1-6 0M12 5v5"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgPower);
export default ForwardRef;
