// packages/vue/src/components/Messages.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <g stroke="currentColor">
      <path
        stroke-miterlimit="10"
        stroke-width="1.5"
        d="M5.63 18.72a1 1 0 0 0-.8-1 3 3 0 0 1-2.2-2.89V9a3 3 0 0 1 3-3h9.6a3 3 0 0 1 3 3v5.86a3 3 0 0 1-3 3h-5.21a1 1 0 0 0-.7.29L6.48 21a.49.49 0 0 1-.85-.35v-1.93Z"
      />
      <path
        stroke-miterlimit="10"
        stroke-width="1.5"
        d="M5.77 6v-.14a3 3 0 0 1 3-3h9.6a3 3 0 0 1 3 3v5.85a3 3 0 0 1-3 3h-.14"
      />
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M7.45 11.85v.001m3-.001v.001m3-.001v.001"
      />
    </g>
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "Messages",
  props: {
    width: {
      required: false,
      type: Number,
      default: () => 16,
    },
    height: {
      required: false,
      type: Number,
      default: () => 16,
    },
  },
});
</script>

// packages/react/src/components/messages.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgMessages = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <g stroke="currentColor">
      <path
        strokeMiterlimit={10}
        strokeWidth={1.5}
        d="M5.63 18.72a1 1 0 0 0-.8-1 3 3 0 0 1-2.2-2.89V9a3 3 0 0 1 3-3h9.6a3 3 0 0 1 3 3v5.86a3 3 0 0 1-3 3h-5.21a1 1 0 0 0-.7.29L6.48 21a.49.49 0 0 1-.85-.35v-1.93Z"
      />
      <path
        strokeMiterlimit={10}
        strokeWidth={1.5}
        d="M5.77 6v-.14a3 3 0 0 1 3-3h9.6a3 3 0 0 1 3 3v5.85a3 3 0 0 1-3 3h-.14"
      />
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M7.45 11.85v.001m3-.001v.001m3-.001v.001"
      />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgMessages);
export default ForwardRef;
