// packages/vue/src/components/TransferVertical.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Transfer-Vertical">
      <path
        id="Vector"
        d="M6.98001 14.4L10.58 18V6"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M17.02 9.6L13.42 6V18"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TransferVertical",
});
</script>

// packages/react/src/components/TransferVertical.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgTransferVertical = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m6.98 14.4 3.6 3.6V6m6.44 3.6L13.42 6v12"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgTransferVertical);
export default ForwardRef;
