// packages/vue/components/Transfer-Horizental.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Transfer-Horizental">
      <path
        id="Vector"
        d="M14.4 17.02L18 13.42H6"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M9.6 6.98L6 10.58H18"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Transfer-Horizental",
};
</script>

// packages/react/src/components/TransferHorizental.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgTransferHorizental = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m14.4 17.02 3.6-3.6H6m3.6-6.44L6 10.58h12"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgTransferHorizental);
export default ForwardRef;
