// packages/vue/src/components/Linear/User1Minus.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="M11.75 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2 8h-7a2.5 2.5 0 0 1 0-5h7m6 2.75h-3.5"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "User1Minus",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>

// packages/react/src/components/User1Minus.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser1Minus = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M11.5 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2 8h-7a2.5 2.5 0 0 1 0-5h7m6.5 2.75h-4.5"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgUser1Minus);
export default ForwardRef;
