// packages/react/src/components/Linear/DollarsignSquare.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgDollarsignSquare = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M14.67 10V8.67a1.34 1.34 0 0 0-1.34-1.34h-2.66a1.34 1.34 0 0 0-1.34 1.34v.66a1.33 1.33 0 0 0 .54 1.07l4.26 3.2a1.33 1.33 0 0 1 .54 1.07v.66a1.34 1.34 0 0 1-1.34 1.34h-2.66a1.34 1.34 0 0 1-1.34-1.34V14M12 6v12"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M17 3H7a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V7a4 4 0 0 0-4-4Z"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgDollarsignSquare);
export default ForwardRef;

// packages/vue/src/components/Linear/DollarsignSquare.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="M14.67 10V8.67a1.34 1.34 0 0 0-1.34-1.34h-2.66a1.34 1.34 0 0 0-1.34 1.34v.66a1.33 1.33 0 0 0 .54 1.07l4.26 3.2a1.33 1.33 0 0 1 .54 1.07v.66a1.34 1.34 0 0 1-1.34 1.34h-2.66a1.34 1.34 0 0 1-1.34-1.34V14M12 6v12"
    />
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="M17 3H7a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V7a4 4 0 0 0-4-4Z"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "DollarsignSquare",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => "1em",
    },
  },
});
</script>
