// packages/vue/components/Arrow-Right.vue
<template>
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g id="Arrow-Right">
      <path
        id="Vector"
        d="M18 12H6"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
      <path
        id="Vector_2"
        d="M14.4 8.4L18 12L14.4 15.6"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<script lang="ts">
export default {
  name: "Arrow-Right",
};
</script>

// packages/react/components/arrow-right.tsx
import * as React from "react";
import { SVGProps, Ref, forwardRef } from "react";
const SvgArrowRight = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    ref={ref}
    {...props}
  >
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
    >
      <path d="M18 12H6M14.4 8.4 18 12l-3.6 3.6" />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgArrowRight);
export default ForwardRef;
