// packages/vue/src/components/Linear/User3Cross.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="M11.28 10.88a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm-7.5 8.24v-3.31a2 2 0 0 1 1.94-1.94h10.06m1.96 4.97 2.48-2.47m-2.48 0 2.48 2.47"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "User3Cross",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>

// packages/react/components/user-3-cross.tsx
import * as React from "react";
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser3Cross = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    ref={ref}
    {...props}
  >
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
    >
      <path d="M11.11 10.84a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3.61 19.09v-3.32a1.94 1.94 0 0 1 1.93-1.93h10.07M17.21 19.16l3.18-3.18M17.21 15.98l3.18 3.18" />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgUser3Cross);
export default ForwardRef;
