// packages/vue/src/components/Linear/User4Tick.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="M15 17.44 16.57 19 20 15.57m-8.5-5.92a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM4 20a7.49 7.49 0 0 1 11.5-6.34"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "User4Tick",
  props: {
    width: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
    height: {
      required: false,
      type: [Number, String],
      default: () => 16,
    },
  },
});
</script>

// packages/react/components/user-4-tick.tsx
import * as React from "react";
import { SVGProps, Ref, forwardRef } from "react";
const SvgUser4Tick = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    ref={ref}
    {...props}
  >
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
    >
      <path d="M15 17.44 16.57 19 20 15.57M11.5 9.65a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM4 20a7.49 7.49 0 0 1 11.5-6.34" />
    </g>
  </svg>
);
const ForwardRef = forwardRef(SvgUser4Tick);
export default ForwardRef;
