// packages/react/src/components/activity.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgActivity = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="m5 15 3.09-4a2 2 0 0 1 3.16 0l1.5 2a2 2 0 0 0 3.16 0L19 9"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgActivity);
export default ForwardRef;

// packages/vue/src/components/Activity.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <path
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      d="m5 15 3.09-4a2 2 0 0 1 3.16 0l1.5 2a2 2 0 0 0 3.16 0L19 9"
    />
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "Activity",
  props: {
    width: {
      required: false,
      type: Number,
      default: () => 16,
    },
    height: {
      required: false,
      type: Number,
      default: () => 16,
    },
  },
});
</script>
