// packages/react/src/components/Linear/LoginRounded.tsx
import { SVGProps, Ref, forwardRef } from "react";
const SvgLoginRounded = (
  props: SVGProps<SVGSVGElement>,
  ref: Ref<SVGSVGElement>
) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={props.width || 16}
    height={props.height || 16}
    ref={ref}
    {...props}
  >
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M16 16a5 5 0 1 1-10 0V8a5 5 0 1 1 10 0m-7 3.73h12"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M12.6 15.33 9 11.73l3.6-3.6"
    />
  </svg>
);
const ForwardRef = forwardRef(SvgLoginRounded);
export default ForwardRef;

// packages/vue/src/components/Login-Rounded.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    :width="width"
    :height="height"
  >
    <g
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
    >
      <path d="M16 16a5 5 0 1 1-10 0V8a5 5 0 1 1 10 0m-7 3.73h12" />
      <path d="M12.6 15.33 9 11.73l3.6-3.6" />
    </g>
  </svg>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "Login-Rounded",
  props: {
    width: {
      required: false,
      type: Number,
      default: () => 16,
    },
    height: {
      required: false,
      type: Number,
      default: () => 16,
    },
  },
});
</script>
